package pojos;
// Generated Nov 1, 2018 12:09:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Penyewaan generated by hbm2java
 */
public class Penyewaan  implements java.io.Serializable {


     private int nik;
     private String nama;
     private Integer nomorHp;
     private String alamat;
     private Date tglSewa;
     private Date tglKembali;

    public Penyewaan() {
    }

	
    public Penyewaan(int nik) {
        this.nik = nik;
    }
    public Penyewaan(int nik, String nama, Integer nomorHp, String alamat, Date tglSewa, Date tglKembali) {
       this.nik = nik;
       this.nama = nama;
       this.nomorHp = nomorHp;
       this.alamat = alamat;
       this.tglSewa = tglSewa;
       this.tglKembali = tglKembali;
    }
   
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Integer getNomorHp() {
        return this.nomorHp;
    }
    
    public void setNomorHp(Integer nomorHp) {
        this.nomorHp = nomorHp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Date getTglSewa() {
        return this.tglSewa;
    }
    
    public void setTglSewa(Date tglSewa) {
        this.tglSewa = tglSewa;
    }
    public Date getTglKembali() {
        return this.tglKembali;
    }
    
    public void setTglKembali(Date tglKembali) {
        this.tglKembali = tglKembali;
    }




}


