package pojos;
// Generated Nov 28, 2018 2:33:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Penyewaan generated by hbm2java
 */
public class Penyewaan  implements java.io.Serializable {


     private int nik;
     private String nama;
     private int nomorHp;
     private String alamat;
     private Date tglSewa;
     private Date tglKembali;
     private int harga;
     private String idPlayStation;

    public Penyewaan() {
    }

    public Penyewaan(int nik, String nama, int nomorHp, String alamat, Date tglSewa, Date tglKembali, int harga, String idPlayStation) {
       this.nik = nik;
       this.nama = nama;
       this.nomorHp = nomorHp;
       this.alamat = alamat;
       this.tglSewa = tglSewa;
       this.tglKembali = tglKembali;
       this.harga = harga;
       this.idPlayStation = idPlayStation;
    }
   
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public int getNomorHp() {
        return this.nomorHp;
    }
    
    public void setNomorHp(int nomorHp) {
        this.nomorHp = nomorHp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Date getTglSewa() {
        return this.tglSewa;
    }
    
    public void setTglSewa(Date tglSewa) {
        this.tglSewa = tglSewa;
    }
    public Date getTglKembali() {
        return this.tglKembali;
    }
    
    public void setTglKembali(Date tglKembali) {
        this.tglKembali = tglKembali;
    }
    public int getHarga() {
        return this.harga;
    }
    
    public void setHarga(int harga) {
        this.harga = harga;
    }
    public String getIdPlayStation() {
        return this.idPlayStation;
    }
    
    public void setIdPlayStation(String idPlayStation) {
        this.idPlayStation = idPlayStation;
    }




}


