package pojos;
// Generated Nov 28, 2018 2:33:35 PM by Hibernate Tools 4.3.1



/**
 * Playstation generated by hbm2java
 */
public class Playstation  implements java.io.Serializable {


     private String idPlayStation;
     private String namaPlayStation;
     private int hargaSewaPlayStation;
     private String status;

    public Playstation() {
    }

    public Playstation(String idPlayStation, String namaPlayStation, int hargaSewaPlayStation, String status) {
       this.idPlayStation = idPlayStation;
       this.namaPlayStation = namaPlayStation;
       this.hargaSewaPlayStation = hargaSewaPlayStation;
       this.status = status;
    }
   
    public String getIdPlayStation() {
        return this.idPlayStation;
    }
    
    public void setIdPlayStation(String idPlayStation) {
        this.idPlayStation = idPlayStation;
    }
    public String getNamaPlayStation() {
        return this.namaPlayStation;
    }
    
    public void setNamaPlayStation(String namaPlayStation) {
        this.namaPlayStation = namaPlayStation;
    }
    public int getHargaSewaPlayStation() {
        return this.hargaSewaPlayStation;
    }
    
    public void setHargaSewaPlayStation(int hargaSewaPlayStation) {
        this.hargaSewaPlayStation = hargaSewaPlayStation;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


