package pojos;
// Generated Nov 1, 2018 12:09:47 PM by Hibernate Tools 4.3.1



/**
 * Playstation generated by hbm2java
 */
public class Playstation  implements java.io.Serializable {


     private String idPlayStation;
     private String namaPlayStation;
     private Integer hargaSewaPlayStation;

    public Playstation() {
    }

	
    public Playstation(String idPlayStation) {
        this.idPlayStation = idPlayStation;
    }
    public Playstation(String idPlayStation, String namaPlayStation, Integer hargaSewaPlayStation) {
       this.idPlayStation = idPlayStation;
       this.namaPlayStation = namaPlayStation;
       this.hargaSewaPlayStation = hargaSewaPlayStation;
    }
   
    public String getIdPlayStation() {
        return this.idPlayStation;
    }
    
    public void setIdPlayStation(String idPlayStation) {
        this.idPlayStation = idPlayStation;
    }
    public String getNamaPlayStation() {
        return this.namaPlayStation;
    }
    
    public void setNamaPlayStation(String namaPlayStation) {
        this.namaPlayStation = namaPlayStation;
    }
    public Integer getHargaSewaPlayStation() {
        return this.hargaSewaPlayStation;
    }
    
    public void setHargaSewaPlayStation(Integer hargaSewaPlayStation) {
        this.hargaSewaPlayStation = hargaSewaPlayStation;
    }




}


